// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqzwlrvuybhnswiessre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxendscnZ1eWJobnN3aWVzc3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzkzNjgsImV4cCI6MjA2Mzg1NTM2OH0.G8j4Sn_toN3y15QnzY0jxv1KjIHzAjAHZXgHVwfvhts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);